# Site settings
title: Byron Williams
email: byron@112percent.com
baseurl: ""
url: "http://www.112percent.com"
twitter_username: "rowanoulton"
github_username:  "rowanoulton"
instagram_username: "rowanoulton"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Pagination
paginate: 25

# Sass
sass:
    style: :compressed

# Build settings
permalink: /:year-:month-:day-:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
    - jekyll-paginate
    - jekyll-sitemap